name: upload images

on:
  push:
    paths:
      'test/*'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    
    - name: Check out repository code
      uses: actions/checkout@v2
      
    - id: files
      uses: jitterbit/get-changed-files@v1
      
    - run: |
        if [ $GITHUB_BASE_REF ]; then
            # Pull Request
            git fetch origin $GITHUB_BASE_REF --depth=1
            export DIFF=$( git diff --name-only origin/$GITHUB_BASE_REF $GITHUB_SHA )
            echo "Diff between origin/$GITHUB_BASE_REF and $GITHUB_SHA"
        else
            # Push
            git fetch origin ${{ github.event.before }} --depth=1
            export DIFF=$( git diff --name-only ${{ github.event.before }} $GITHUB_SHA )
            echo "Diff between ${{ github.event.before }} and $GITHUB_SHA"
        fi
        echo "$DIFF"
        files="${{ steps.files.outputs.all }}"
        for fullpath in test/*; do
          mimetype=$(file -b --mime-type $fullpath)
          ls $fullpath -lh
          file $fullpath
          echo $mimetype
          if [[ $mimetype =~ "image" ]]; then
             filename="${fullpath##*/}"
             dir="${fullpath:0:${#fullpath} - ${#filename}}"
             base="${filename%.[^.]*}"
             ext="${filename:${#base} + 1}"                 
             convert -resize 140x140\! $fullpath /tmp/$base.png
             ls /tmp
          fi
          echo "Do something with this $fullpath."
        done
