name: upload images

on:
  push:
    paths:
      'test/*'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    
    - id: files
      uses: jitterbit/get-changed-files@v1
      
    - run: |
        files="${{ steps.files.outputs.all }}"
        for fullpath in $files; do
          mimetype=$(file -b --mime-type $fullpath)
          if [[ $mimetype =~ "image" ]]; then
             filename="${fullpath##*/}"
             dir="${fullpath:0:${#fullpath} - ${#filename}}"
             base="${filename%.[^.]*}"
             ext="${filename:${#base} + 1}"                 
             convert -resize 140x140\! $fullpath $base.png 
          fi
          echo "Do something with this $fullpath."
        done
