name: upload images

on:
  push:
    paths:
      'test/*'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    
    - name: Check out repository code
      uses: actions/checkout@v2
      
    - id: files
      uses: jitterbit/get-changed-files@v1
      
    - name: Install s5cmd
      run: wget https://github.com/peak/s5cmd/releases/download/v1.4.0/s5cmd_1.4.0_Linux-64bit.tar.gz -qO- | tar -xz

    - env: 
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
        S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT }}
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}
      run: |
        folders=("test")
        files=${{ steps.files.outputs.all }}
      
        for fullpath in $files; do
          filename="${fullpath##*/}"
          dir="${fullpath%%/*}"
          [[ $filename == $dir ]] && continue
          [[ " ${foldes[*]} " =~ " ${dir} " ]] || continue
          mimetype=$(file -b --mime-type $fullpath)
          if [[ $mimetype =~ "image" ]]; then
             dirpath="${fullpath:0:${#fullpath} - ${#filename}}"
             base="${filename%.[^.]*}"
             ext="${filename:${#base} + 1}"                 
             convert -resize 140x140\! $fullpath /tmp/$base.png
             ./s5cmd cp -acl public-read /tmp/$base.png s3://$S3_BUCKET/$dirpath$base.png
          fi
        done
